# Common kafka broker environment variables
x-kafka-broker-env: &kafka-broker-env
    KAFKA_ENABLE_KRAFT: "true"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
#    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SASL_SSL,PLAINTEXT:SASL_SSL'
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
    KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@broker-1:9094,2@broker-2:9094,3@broker-3:9094'
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    KAFKA_JMX_HOSTNAME: localhost
    KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    ALLOW_PLAINTEXT_LISTENER: "true"
    KAFKA_METADATA_LOG_DIR: /tmp/kraft-metadata-logs
    KAFKA_KRAFT_CLUSTER_ID: 77aa4755-2806-4237-aff8-6e874c300da0
    USER: "0"
#    KAFKA_CFG_LOG_LEVEL: "DEBUG"

# Common kafka broker configuration
x-kafka-broker-common: &kafka-broker-common
  image: 'bitnami/kafka:3.3.1'
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
#    tcp_server:
#        build:
#            context: .
#            dockerfile: .docker/python/Dockerfile
#        container_name: tcp_server
#        ports:
#            - "6020:6020"  # Port pour votre serveur TCP
#        volumes:
#            - ./src:/app
#        environment:
#            - TCP_HOST=0.0.0.0
#            - TCP_PORT=6020
#            - KAFKA_BROKERS=broker-1:9092,broker-2:9093,broker-3:9094
#            - MONGO_URI=mongodb://mongo:27017
#        depends_on:
#            - kafka
#            - mongo
#        restart: always

    mqtt-broker:
        image: eclipse-mosquitto:2.0.15
        container_name: mqtt-broker
        ports:
            - "1883:1883" # Port MQTT standard
        volumes:
            - ./.docker/mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        restart: always

#    broker-1:
#        <<: *kafka-broker-common
#        container_name: broker-1
#        ports:
#            - "9192:9092"
#        environment:
#            <<: *kafka-broker-env  # Référence à l'ancrage défini ci-dessus
#            KAFKA_CFG_BROKER_ID: 1
#            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9094,PLAINTEXT_HOST://0.0.0.0:9092
#            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:9092,PLAINTEXT_HOST://localhost:9092
#            KAFKA_JMX_PORT: 9996
#        volumes:
#            - broker_1_data:/var/lib/kafka/data
#        healthcheck:
#            test: nc -vz localhost 9192
#            interval: 10s
#            timeout: 10s
#            retries: 3
#        restart: always
#
#    broker-2:
#        <<: *kafka-broker-common
#        container_name: broker-2
#        ports:
#            - "9292:9092"
#        environment:
#            <<: *kafka-broker-env  # Référence à l'ancrage défini ci-dessus
#            KAFKA_CFG_BROKER_ID: 2
#            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9094,PLAINTEXT_HOST://0.0.0.0:9092
#            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker-2:9092,PLAINTEXT_HOST://localhost:9092
#            KAFKA_JMX_PORT: 9996
#        volumes:
#            - broker_2_data:/var/lib/kafka/data
#        healthcheck:
#            test: nc -vz localhost 9292
#            interval: 10s
#            timeout: 10s
#            retries: 3
#        restart: always
#
#    broker-3:
#        <<: *kafka-broker-common
#        container_name: broker-3
#        hostname: broker-3
#        ports:
#            - "9392:9092"
#        environment:
#            KAFKA_CFG_BROKER_ID: 3
#            <<: *kafka-broker-env  # Référence à l'ancrage défini ci-dessus
#            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9094,PLAINTEXT_HOST://0.0.0.0:9092
#            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://broker-3:9092,PLAINTEXT_HOST://localhost:9092
#            KAFKA_JMX_PORT: 9996
#        volumes:
#            - broker_3_data:/var/lib/kafka/data
#        healthcheck:
#            test: nc -vz localhost 9392
#            interval: 10s
#            timeout: 10s
#            retries: 3
#        restart: always
#
#    kafka-ui:
#        container_name: kafka-ui
#        image: 'provectuslabs/kafka-ui:latest'
#        ports:
#            - "8087:8080"
#        environment:
#            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker-1:9092
#            - KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA
#            - KAFKA_CLUSTERS_0_METRICS_PORT=9996
#            - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=broker-2:9093
#            - KAFKA_CLUSTERS_1_NAME=broker-2
#            - KAFKA_CLUSTERS_1_METRICS_PORT=9997
#            - KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS=broker-3:9094
#            - KAFKA_CLUSTERS_2_NAME=broker-3
#            - KAFKA_CLUSTERS_2_METRICS_PORT=9998
#            - DYNAMIC_CONFIG_ENABLED="true"
#            - KAFKA_SECURITY_ENABLED=true # Activer la sécurité
#            - KAFKA_SECURITY_USERNAME=admin
#            - KAFKA_SECURITY_PASSWORD=Admin123
#        depends_on:
#            - broker-1
#            - broker-2
#            - broker-3

    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
          - ./.docker/mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
          - mongodb-data:/data/db/
          - mongodb-log:/var/log/mongodb/
        env_file:
          - .env
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
          - "${MONGODB_PORT}:${MONGODB_PORT}"
#        networks:
#          - mongodb_network
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 5s
            retries: 5

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
            ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_SERVER}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
        ports:
            - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
#        networks:
#            - mongodb_network
        depends_on:
            - mongodb

#    consumer:
#        build:
#            context: .
#            dockerfile: .docker/python/Dockerfile
#        volumes:
#            - ./src:/app
#        command: python /app/consumer.py
#        depends_on:
#            - kafka_custom


volumes:
    broker_1_data:
        driver: local
    broker_2_data:
        driver: local
    broker_3_data:
        driver: local
    mongodb-data:
        driver: local
        name: mongo-data
    mongodb-log:
        driver: local
        name: mongo-log