# Common kafka broker environment variables
x-kafka-broker-env: &kafka-broker-env
    KAFKA_ENABLE_KRAFT: "true"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
#    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SASL_SSL,PLAINTEXT:SASL_SSL'
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
    KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@broker-1:9094,2@broker-2:9094,3@broker-3:9094'
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    KAFKA_JMX_HOSTNAME: localhost
    KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    ALLOW_PLAINTEXT_LISTENER: "true"
    KAFKA_METADATA_LOG_DIR: /tmp/kraft-metadata-logs
    KAFKA_KRAFT_CLUSTER_ID: 77aa4755-2806-4237-aff8-6e874c300da0
    USER: "0"
#    KAFKA_CFG_LOG_LEVEL: "DEBUG"

# Common kafka broker configuration
x-kafka-broker-common: &kafka-broker-common
  image: 'bitnami/kafka:3.3.1'
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
    tcp_server:
        build:
          context: .
          dockerfile: ./.docker/python/Dockerfile
        image: tcp-server-health
        container_name: tcp_server
        ports:
          - "6020:6020"
        volumes:
          - ./src:/src
        env_file:
            - .env
        environment:
          - TCP_HOST=0.0.0.0
          - TCP_PORT=6020
          - MONGO_URI=${MONGO_URI}
        depends_on:
          - mqtt-broker
          - mongodb
        restart: always

    mqtt-broker:
        image: eclipse-mosquitto:2.0.15
        container_name: mqtt-broker
        ports:
            - "1883:1883"
        volumes:
            - ./.docker/mosquitto/config:/mosquitto/config
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
        restart: always

    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./.docker/mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongodb-data:/data/db/
            - mongodb-log:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_DATABASE: "${MONGO_DB_NAME}"
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
            MONGO_URI: "${MONGO_URI}"
        ports:
            - "${MONGODB_PORT}:${MONGODB_PORT}"
        restart: always
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 5s
            retries: 5

    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
            ME_CONFIG_MONGODB_PORT: "${MONGODB_PORT}"
            ME_CONFIG_MONGODB_URL: "${ME_CONFIG_MONGODB_SERVER}"
            ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_EXPRESS_USERNAME}"
            ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_EXPRESS_PASSWORD}"
        ports:
            - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
        depends_on:
            - mongodb
        restart: always

    api-web:
        build:
            context: .
            dockerfile: ./.docker/fast_api/Dockerfile
        image: api-web-health
        container_name: api-web
        ports:
            - "8000:80"
        volumes:
            - ./src:/src
        env_file:
            - .env
        depends_on:
            - mongodb
        restart: always

volumes:
    mongodb-data:
        driver: local
        name: mongo-data
    mongodb-log:
        driver: local
        name: mongo-log
    mosquitto_data:
        driver: local
        name: mosquitto_log
    mosquitto_log:
        driver: local
        name: mosquitto_log